server:
  port: 8080

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:h2:file:./userdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: nik
    password: nik
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-user
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
