server:
  port: 8082

spring:
  application:
    name: card-service

  datasource:
    url: jdbc:h2:mem:cartDb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1 #TODO ??????? ???? ?????? ? memory. ???? ?? ?? ??????? H2
    driverClassName: org.h2.Driver
    username: nik
    password: nik
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-cart

